# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: internal-it@quansight.com
author_name: Nebari development team
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab-launchpad
mimetype: ''
mimetype_name: ''
project_short_description: A redesigned JupyterLab launcher
python_name: jupyterlab_launchpad
repository: https://github.com/nebari-dev/jupyterlab-launchpad
test: true
viewer_name: ''

